### ISSUE TITLE
Django 2.1 incompatibility.

### ISSUE THREAD

**Issue by dubirajara** [summernote/django-summernote#309]
Hi,

I have updated the version of my project for django 2.1, and I am having problem to render forms, I get error :

TypeError: render () got an unexpected keyword argument 'renderer'

Django 2.1 release says, Feature removed in 2.1:

"Support for Widget.render ( ) methods without the renderer argument is removed. "

if it's helpful, I've managed to solve it, modifying the method "render" of the class "SummernoteWidget", I have added "renderer=None" in django_summernote/widgets.py:

`def render(self, name, value, attrs=None, renderer=None):`

![captura de pantalla 2018-08-04 a las 14 47 30](https://user-images.githubusercontent.com/15200556/43676653-6168d2be-97f5-11e8-9ba0-d78da2503ea6.png)

this solution is correct to solve this problem, can you give us a release that works with 2.1 or can I send a pr?

thanks.
